In [2]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [5]:
df = pd.read_csv('german_credit_data_updated.csv')

In [6]:
df.head(10)

,Unnamed: 0,Age,Sex,Job,Housing,Saving accounts,Checking account,Credit amount,Duration,Purpose,Credit Risk
0,0,67,male,2,own,NaN,little,1169,6,radio/TV,1
1,1,22,female,2,own,little,moderate,5951,48,radio/TV,2
2,2,49,male,1,own,little,NaN,2096,12,education,1
3,3,45,male,2,free,little,little,7882,42,furniture/equipment,1
4,4,53,male,2,free,little,little,4870,24,car,2
5,5,35,male,1,free,NaN,NaN,9055,36,education,1
6,6,53,male,2,own,quite rich,NaN,2835,24,furniture/equipment,1
7,7,35,male,3,rent,little,moderate,6948,36,car,1
8,8,61,male,1,own,rich,NaN,3059,12,radio/TV,1
9,9,28,male,3,own,little,moderate,5234,30,car,2

In [7]:
df.columns = [col.lower().replace(' ', '_') for col in df.columns]

In [8]:
df.head(10)

,unnamed:_0,age,sex,job,housing,saving_accounts,checking_account,credit_amount,duration,purpose,credit_risk
0,0,67,male,2,own,NaN,little,1169,6,radio/TV,1
1,1,22,female,2,own,little,moderate,5951,48,radio/TV,2
2,2,49,male,1,own,little,NaN,2096,12,education,1
3,3,45,male,2,free,little,little,7882,42,furniture/equipment,1
4,4,53,male,2,free,little,little,4870,24,car,2
5,5,35,male,1,free,NaN,NaN,9055,36,education,1
6,6,53,male,2,own,quite rich,NaN,2835,24,furniture/equipment,1
7,7,35,male,3,rent,little,moderate,6948,36,car,1
8,8,61,male,1,own,rich,NaN,3059,12,radio/TV,1
9,9,28,male,3,own,little,moderate,5234,30,car,2

In [11]:
if 'Unnamed: 0' in df.columns: df.drop(columns=['Unnamed: 0'], inplace=True)
df.columns = [col.lower().replace(' ', '_') for col in df.columns]

In [12]:
df['saving_accounts'] = df['saving_accounts'].fillna('none/unknown')
df['checking_account'] = df['checking_account'].fillna('none/unknown')

In [13]:
df.head(10)

,unnamed:_0,age,sex,job,housing,saving_accounts,checking_account,credit_amount,duration,purpose,credit_risk
0,0,67,male,2,own,none/unknown,little,1169,6,radio/TV,1
1,1,22,female,2,own,little,moderate,5951,48,radio/TV,2
2,2,49,male,1,own,little,none/unknown,2096,12,education,1
3,3,45,male,2,free,little,little,7882,42,furniture/equipment,1
4,4,53,male,2,free,little,little,4870,24,car,2
5,5,35,male,1,free,none/unknown,none/unknown,9055,36,education,1
6,6,53,male,2,own,quite rich,none/unknown,2835,24,furniture/equipment,1
7,7,35,male,3,rent,little,moderate,6948,36,car,1
8,8,61,male,1,own,rich,none/unknown,3059,12,radio/TV,1
9,9,28,male,3,own,little,moderate,5234,30,car,2

In [14]:
df['default_status'] = df['credit_risk'].apply(lambda x: 1 if x == 2 else 0)

In [15]:
df.head(10)

,unnamed:_0,age,sex,job,housing,saving_accounts,checking_account,credit_amount,duration,purpose,credit_risk,default_status
0,0,67,male,2,own,none/unknown,little,1169,6,radio/TV,1,0
1,1,22,female,2,own,little,moderate,5951,48,radio/TV,2,1
2,2,49,male,1,own,little,none/unknown,2096,12,education,1,0
3,3,45,male,2,free,little,little,7882,42,furniture/equipment,1,0
4,4,53,male,2,free,little,little,4870,24,car,2,1
5,5,35,male,1,free,none/unknown,none/unknown,9055,36,education,1,0
6,6,53,male,2,own,quite rich,none/unknown,2835,24,furniture/equipment,1,0
7,7,35,male,3,rent,little,moderate,6948,36,car,1,0
8,8,61,male,1,own,rich,none/unknown,3059,12,radio/TV,1,0
9,9,28,male,3,own,little,moderate,5234,30,car,2,1

In [16]:
df['monthly_burden'] = df['credit_amount'] / df['duration']

In [17]:
df.head(10)

,unnamed:_0,age,sex,job,housing,saving_accounts,checking_account,credit_amount,duration,purpose,credit_risk,default_status,monthly_burden
0,0,67,male,2,own,none/unknown,little,1169,6,radio/TV,1,0,194.833333
1,1,22,female,2,own,little,moderate,5951,48,radio/TV,2,1,123.979167
2,2,49,male,1,own,little,none/unknown,2096,12,education,1,0,174.666667
3,3,45,male,2,free,little,little,7882,42,furniture/equipment,1,0,187.666667
4,4,53,male,2,free,little,little,4870,24,car,2,1,202.916667
5,5,35,male,1,free,none/unknown,none/unknown,9055,36,education,1,0,251.527778
6,6,53,male,2,own,quite rich,none/unknown,2835,24,furniture/equipment,1,0,118.125000
7,7,35,male,3,rent,little,moderate,6948,36,car,1,0,193.000000
8,8,61,male,1,own,rich,none/unknown,3059,12,radio/TV,1,0,254.916667
9,9,28,male,3,own,little,moderate,5234,30,car,2,1,174.466667

In [18]:
df['age_group'] = pd.cut(df['age'], bins=[18, 30, 45, 60, 100], 
                         labels=['Young Adult', 'Adult', 'Senior', 'Elderly'])

In [19]:
df.head(10)

,unnamed:_0,age,sex,job,housing,saving_accounts,checking_account,credit_amount,duration,purpose,credit_risk,default_status,monthly_burden,age_group
0,0,67,male,2,own,none/unknown,little,1169,6,radio/TV,1,0,194.833333,Elderly
1,1,22,female,2,own,little,moderate,5951,48,radio/TV,2,1,123.979167,Young Adult
2,2,49,male,1,own,little,none/unknown,2096,12,education,1,0,174.666667,Senior
3,3,45,male,2,free,little,little,7882,42,furniture/equipment,1,0,187.666667,Adult
4,4,53,male,2,free,little,little,4870,24,car,2,1,202.916667,Senior
5,5,35,male,1,free,none/unknown,none/unknown,9055,36,education,1,0,251.527778,Adult
6,6,53,male,2,own,quite rich,none/unknown,2835,24,furniture/equipment,1,0,118.125000,Senior
7,7,35,male,3,rent,little,moderate,6948,36,car,1,0,193.000000,Adult
8,8,61,male,1,own,rich,none/unknown,3059,12,radio/TV,1,0,254.916667,Elderly
9,9,28,male,3,own,little,moderate,5234,30,car,2,1,174.466667,Young Adult

In [20]:
def define_risk(row):
    if row['saving_accounts'] == 'little' and row['credit_amount'] > 5000:
        return 'Critical Risk'
    elif row['saving_accounts'] in ['rich', 'quite rich']:
        return 'Low Risk'
    else:
        return 'Standard'

In [21]:
df['risk_tier'] = df.apply(define_risk, axis=1)

In [22]:
df.head(10)

,unnamed:_0,age,sex,job,housing,saving_accounts,checking_account,credit_amount,duration,purpose,credit_risk,default_status,monthly_burden,age_group,risk_tier
0,0,67,male,2,own,none/unknown,little,1169,6,radio/TV,1,0,194.833333,Elderly,Standard
1,1,22,female,2,own,little,moderate,5951,48,radio/TV,2,1,123.979167,Young Adult,Critical Risk
2,2,49,male,1,own,little,none/unknown,2096,12,education,1,0,174.666667,Senior,Standard
3,3,45,male,2,free,little,little,7882,42,furniture/equipment,1,0,187.666667,Adult,Critical Risk
4,4,53,male,2,free,little,little,4870,24,car,2,1,202.916667,Senior,Standard
5,5,35,male,1,free,none/unknown,none/unknown,9055,36,education,1,0,251.527778,Adult,Standard
6,6,53,male,2,own,quite rich,none/unknown,2835,24,furniture/equipment,1,0,118.125000,Senior,Low Risk
7,7,35,male,3,rent,little,moderate,6948,36,car,1,0,193.000000,Adult,Critical Risk
8,8,61,male,1,own,rich,none/unknown,3059,12,radio/TV,1,0,254.916667,Elderly,Low Risk
9,9,28,male,3,own,little,moderate,5234,30,car,2,1,174.466667,Young Adult,Critical Risk

In [24]:
df.to_csv('credit_risk_engineered.csv', index=False)

In [26]:
import pandas as pd
from sqlalchemy import create_engine
import urllib.parse

# 1. Load the engineered data we created in Step 2
df_risk = pd.read_csv('credit_risk_engineered.csv')

# 2. Database Credentials
USER = 'krish'
PASSWORD = 'Mrsavaj@123' # Replace with your actual MySQL password
HOST = '127.0.0.1'
PORT = '3306'
DB_NAME = 'financial_risk_db'

# 3. Securely encode password and create connection
safe_password = urllib.parse.quote_plus(PASSWORD)
connection_string = f"mysql+pymysql://{USER}:{safe_password}@{HOST}:{PORT}/{DB_NAME}"
engine = create_engine(connection_string)

# 4. Push to MySQL
try:
    df_risk.to_sql('german_credit_data', con=engine, if_exists='replace', index=False)
    print("✅ SUCCESS: Financial data uploaded to 'financial_risk_db.german_credit_data'!")
except Exception as e:
    print(f"❌ Error uploading to MySQL: {e}")

✅ SUCCESS: Financial data uploaded to 'financial_risk_db.german_credit_data'!

In [27]:
query = "SELECT risk_tier, COUNT(*) as count, ROUND(AVG(credit_amount), 2) as avg_loan FROM german_credit_data GROUP BY risk_tier"
verification_df = pd.read_sql(query, con=engine)
display(verification_df)

       risk_tier  count  avg_loan
0       Standard    748   2726.69
1  Critical Risk     99   8187.37
2       Low Risk    107   2599.63

In [29]:
df.to_csv('german_credit_data.csv', index=False)
print("File 'german_credit_data.csv' is ready for Power BI!")

File 'german_credit_data.csv' is ready for Power BI!

In [31]:
from IPython.display import FileLink
FileLink('german_credit_data.csv')

C:\Users\krish\german_credit_data.csv